import Head from 'next/head'
// import Image from 'next/image'
// import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import ToDoList from '../components/todolist'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sprinto todo app</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <ToDoList />
    </div>
  )
}
